name: car_track
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ">=1.1.0 <2.0.0"
  redux: ^3.0.0
  flutter_redux: ^0.5.3
  key_value_store_flutter:
  key_value_store_web:
  shared_preferences:
  firebase_core: "^0.5.0+1"
  firebase_auth: "^0.18.1+2"
  google_sign_in: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
